### ISSUE TITLE
Feedback zu Use Cases

### ISSUE THREAD

**Issue by FHausen** [sebastiankoch10/EPWS2223HausenKochZimmer#1]
Hallo, wir würden gerne um Feedback zu unseren spezifizierten Use Cases bitten. [Der Link zum Dokument ](https://github.com/sebastiankoch10/EPWS2223HausenKochZimmer/blob/2a76d1ac9faf1e99350471bff3f1cd2efde1d6c5/Modellierungen/Usecases.docx)

Wir haben die Spezifikation nur für die Use Cases bisher gemacht, die wir auch im Prototypen darstellen wollen. Die Frage wär vor allen Dingen, ob das für den Prototypen ausreicht oder wir noch weitere Use Cases inkludieren sollen.

**Comment by umuesse** [comment]
Hey, 

die UseCases "Subscribe" und "Bild hochladen" (Publish) sind passende UseCases, da sie den Kern eures Systems wiederspiegeln. 
Allerdings würde ich euch raten den "Subscribe"-UseCase noch um den Erhalt der Banachrichtigung nach dem "Publish" erweitern, sodass ersichtlich ist, dass diese FUnktionalität vorhanden ist und das Abonnement auch wirklich funktioniert. 
Entsprechend wäre das Löschen des Abos evtl. auch noch sinnvoll, um zu zeigen, dass die Aktualisierung (bspw. durch einen Kommentar zum Bild) nicht mehr durchkommt, wenn das Abo gelöscht wurde.  

Den UseCase "LogIn" würde ich vermutlich ausklammern, da er wenig repräsentativ für euer System ist.
